# Generated by Django 6.0.2 on 2026-03-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='url_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
