# Generated by Django 6.0.2 on 2026-03-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authinventory', '0002_alter_drink_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
