# Generated by Django 6.0.2 on 2026-03-09 12:12

import authinventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authinventory', '0003_alter_drink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='url_img',
            field=models.ImageField(blank=True, null=True, upload_to=authinventory.models.drink_image_path),
        ),
    ]
