# Generated by Django 6.0.2 on 2026-03-03 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0002_alter_roles_id_alter_status_id_alter_typedocument_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authusers.status'),
        ),
    ]
