# Generated by Django 6.0.2 on 2026-02-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0003_alter_user_id_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
