"""
Django settings for nightcodeapi project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import unquote, urlparse, urlsplit

from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.getenv(name)
    if value is None:
        return default or []
    return [item.strip() for item in value.split(',') if item.strip()]


def env_str(name: str, default: str = '') -> str:
    value = os.getenv(name)
    return value.strip() if value is not None else default


def normalize_origin(value: str) -> str:
    value = value.strip()
    if not value:
        return value

    parts = urlsplit(value)
    if parts.scheme and parts.netloc:
        return f'{parts.scheme}://{parts.netloc}'

    return value.rstrip('/')


def normalize_origin_list(values: list[str]) -> list[str]:
    normalized: list[str] = []
    for value in values:
        origin = normalize_origin(value)
        if origin and origin not in normalized:
            normalized.append(origin)
    return normalized


def resolve_media_root() -> str:
    configured_media_root = env_str('MEDIA_ROOT')

    candidates = []
    if configured_media_root:
        candidates.append(Path(configured_media_root))

    if DEBUG:
        candidates.append(BASE_DIR / 'media')

    # /tmp is writable on Render even when no persistent disk is mounted.
    candidates.append(Path('/tmp/nightcode-media'))

    for candidate in candidates:
        try:
            candidate.mkdir(parents=True, exist_ok=True)
            return str(candidate)
        except OSError:
            continue

    raise ValueError('Could not determine a writable MEDIA_ROOT path.')


def build_database_config() -> dict:
    database_url = os.getenv('DATABASE_URL', '').strip()
    if database_url:
        parsed = urlparse(database_url)
        scheme = parsed.scheme.lower()
        if scheme in {'postgres', 'postgresql'}:
            return {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': unquote(parsed.path.lstrip('/')),
                'USER': unquote(parsed.username or ''),
                'PASSWORD': unquote(parsed.password or ''),
                'HOST': parsed.hostname or '',
                'PORT': str(parsed.port or '5432'),
            }
        if scheme == 'sqlite':
            sqlite_path = unquote(parsed.path or '').lstrip('/')
            if not sqlite_path:
                sqlite_path = str(BASE_DIR / 'db.sqlite3')
            return {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': sqlite_path,
            }

    db_name = os.getenv('DB_NAME')
    if db_name:
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }

    if env_bool('DEBUG', True) and env_bool('DEV_USE_SQLITE', True):
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env_bool('DEBUG', True)

SECRET_KEY = env_str('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key-change-me'
    else:
        raise ValueError('SECRET_KEY is required when DEBUG is False')

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    ['127.0.0.1', 'localhost']
)

render_external_hostname = env_str('RENDER_EXTERNAL_HOSTNAME')
if render_external_hostname and render_external_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_external_hostname)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'channels',
    'corsheaders',
    'authusers',
    'authinventory',
    'order',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', False)
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    [
        "https://nightcodefrontend.vercel.app",
        'http://localhost:3000',
        'http://127.0.0.1:3000',

    ],
)
CORS_ALLOWED_ORIGINS = normalize_origin_list(CORS_ALLOWED_ORIGINS)
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ],
)
CSRF_TRUSTED_ORIGINS = normalize_origin_list(CSRF_TRUSTED_ORIGINS)

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

render_external_url = env_str('RENDER_EXTERNAL_URL')
if render_external_url:
    render_external_url = normalize_origin(render_external_url)
    if render_external_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(render_external_url)
    if render_external_url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_external_url)

ROOT_URLCONF = 'nightcodeapi.urls'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nightcodeapi.wsgi.application'
ASGI_APPLICATION = 'nightcodeapi.asgi.application'

REDIS_URL = env_str('REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': build_database_config()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'authusers.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = resolve_media_root()


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

FRONTEND_MENU_BASE_URL = os.getenv(
    'FRONTEND_MENU_BASE_URL',
    'http://127.0.0.1:3000/order'
)

CALL_WAITER_STRICT_TOKEN = env_bool('CALL_WAITER_STRICT_TOKEN', False)
CALL_WAITER_STATUS_NAME = os.getenv(
    'CALL_WAITER_STATUS_NAME', 'Llamando mesero')

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SECURE_HSTS_SECONDS = int(env_str('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
