# Generated by Django 6.0.2 on 2026-02-16 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
            },
        ),
        migrations.CreateModel(
            name='typeDrinkTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de bebida',
                'verbose_name_plural': 'Tipos de bebidas',
            },
        ),
        migrations.CreateModel(
            name='typeOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'estado nombre',
                'verbose_name_plural': 'estado nombres',
            },
        ),
        migrations.CreateModel(
            name='typeStatusTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_users', models.ForeignKey(db_column='id_users', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('id_payment', models.ForeignKey(blank=True, db_column='id_payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.paymentmethod')),
                ('id_mesa', models.ForeignKey(db_column='id_mesa', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.typedrinktables')),
                ('id_order_status', models.ForeignKey(db_column='id_order_status', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.typeorderstatus')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_order', models.ForeignKey(db_column='id_order', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='order.order')),
                ('id_drink', models.ForeignKey(db_column='id_drink', on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='order.typedrinktables')),
            ],
            options={
                'verbose_name': 'Detalle de orden',
                'verbose_name_plural': 'Detalles de orden',
            },
        ),
        migrations.AddField(
            model_name='typedrinktables',
            name='status',
            field=models.ForeignKey(db_column='id_Status', on_delete=django.db.models.deletion.PROTECT, related_name='drinks', to='order.typestatustables'),
        ),
    ]
