# Generated by Django 6.0.2 on 2026-03-03 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authinventory', '0001_initial'),
        ('order', '0002_alter_order_id_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_details_real', to='authinventory.drink'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_users',
            field=models.ForeignKey(db_column='id_users', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
