# Generated by Django 6.0.2 on 2026-03-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderdetail_id_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
